---
title: "Hello World for Medical Images"
author: "Matthew Emery"
date: "January 20, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(keras)
library(rprojroot)
library(fs)
```

```{r}
img_height <- 299L
img_width <- 299L
```

```{r}
root <- find_root(has_dir(".git"))
train_data_directory <- path(root, "data", "TRAIN")
validation_data_directory <- path(root, "data", "VAL")
```

```{r}
train_samples <- 65L
validation_samples <- 10L
epochs <- 20L
batch_size <- 5L
```

```{r}
train_data_generator <- image_data_generator(
  rescale = 1/255,
  shear_range = 0.2,
  zoom_range = 0.2,
  rotation_range = 20,
  width_shift_range = 0.2,
  height_shift_range = 0.2,
  horizontal_flip = TRUE
)
```

```{r}
validation_data_generator <- image_data_generator(
  rescale = 1/255
)
```

```{r}
train_generator <- train_data_generator$flow_from_directory(
  train_data_directory,
  target_size = c(img_height, img_width),
  batch_size = batch_size,
  class_mode = "binary"
)
```

```{r}
validation_generator <- validation_data_generator$flow_from_directory(
  validation_data_directory,
  target_size = c(img_height, img_width),
  batch_size = batch_size,
  class_mode = "binary"
)
```

```{r}
base_model <- application_inception_v3(
  weights = "imagenet",
  include_top = FALSE,
  input_shape = c(img_width, img_height, 3L)
)
```


```{r}
for (layer in base_model$layers)
  layer$trainable <- TRUE
```


```{r}
model_top <- base_model$output %>% 
  layer_global_average_pooling_2d(trainable = TRUE) %>% 
  layer_dense(256L, 
              activation = "relu",
              trainable = TRUE) %>% 
  layer_dropout(0.5) %>% 
  layer_dense(1L,
              trainable = TRUE,
              activation = "sigmoid")
```

```{r}
full_model <- keras_model(
  inputs = base_model$input,
  outputs = model_top) %>% 
  keras::compile(
    optimizer = optimizer_adam(
      lr = 0.0001,
      epsilon = 1e-08
    ),
    loss = "binary_crossentropy",
    metrics = c("accuracy")
  )  
```

# TODO: Should probably freeze Inception weights

```{r}
history <- fit_generator(
  full_model,
  generator = train_generator,
  steps_per_epoch = as.integer(train_samples / batch_size),
  epochs = epochs,
  validation_data = validation_generator,
  validation_steps = as.integer(validation_samples / batch_size)
)
```

```{r}
summary(full_model)
```


## Bibliography
